# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: docker-php-ext-install intl
      - run: vendor/bin/phpunit --configuration dev/tests/phpunit.xml --testsuite unit --coverage-clover clover.xml
